name: olive-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pandas>=1.5.0
  - numpy>=1.21.0
  - dash>=2.9.0
  - dash-bootstrap-components>=1.4.0
  - plotly>=5.13.0
  - tensorflow>=2.14.0
  - keras>=2.14.0
  - scikit-learn==1.5.2
  - joblib>=1.2.0
  - python-dotenv>=0.21.0
  - psutil>=5.9.0
  - dvc>=2.0.0
  - pip
  - pip:
      - dash-bootstrap-components>=1.4.0